<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: proutyr1
 * Date: Fri, 20 Oct 2023 14:25:10 -0400
 */

$conf['title'] = 'UMBC Observatory Wiki';
$conf['template'] = 'bootstrap3';
$conf['sidebar'] = 'Sidebar';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['authtype'] = 'oauth';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,resendpwd,profile_delete';
$conf['useslash'] = 1;
$conf['plugin']['confightmlok']['use_sure'] = 1;
$conf['plugin']['confightmlok']['use_really_sure'] = 1;
$conf['plugin']['mathjax']['config'] = 'MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ["$","$"], ["\\\\(","\\\\)"] ],
        displayMath: [ ["$$","$$"], ["\\\\[","\\\\]"] ],
        processEscapes: true
    }
});';
$conf['plugin']['oauth']['mailRestriction'] = '@umbc.edu';
$conf['plugin']['oauth']['singleService'] = 1;
$conf['plugin']['oauthgoogle']['key'] = '415863886675-6rrfodtgo27rqomj2peppfr3p43kfjuv.apps.googleusercontent.com';
$conf['plugin']['oauthgoogle']['secret'] = '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';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'darkly';
$conf['tpl']['bootstrap3']['rightSidebar'] = 'leftsidebar';
$conf['tpl']['bootstrap3']['sidebarOnNavbar'] = 1;
$conf['tpl']['bootstrap3']['useACL'] = 1;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
